### ISSUE TITLE
[cooker] Add a way to get asset dimensions with pug

### ISSUE THREAD

**Issue by marlonmarcello** [wethegit/sweet-potato#10]
It's possible to pass data to PUG, like we have `globals` and `page` at the moment.
But it's also possible to pass functions!

On this line of code we set our base data: https://github.com/wethegit/sweet-potato/blob/main/cooker/lib/pages.js#L208
We could add another property there, together with `globals` and `page`, called `functions` that we could use to pass helper functions to pug templates.

```js
const outputOptions = {
      destination: CONSTS.BUILD_DIRECTORY,
      filepath: pagePath,
      filename: `${templateInfo.name}.html`,
      pugFunction: compiledFunction,
      data: {
        globals: {},
        page: {},
        functions: {
          getImageDimensions: functionToGetImageDimensions
        }
      },
    };
```

For this use case, we should probably use [image-size](https://github.com/image-size/image-size#readme) package and pass that to it.

```js
const sizeOf = require('image-size');

// ... CODE
  getImageDimensions: sizeOf
}
```

Then inside of a `.pug` template:
```pug
- const src = "images/wow.jpg"
- const { width, height } = functions.getImageDimension(src)
img(src=src, width=width, height=height)
```

**Comment by andrewrubin** [comment]
Just saw this—great idea. This way we can set aspect ratio/dimensions on our images for lazy loading!

**Comment by marlonmarcello** [comment]
Exactly!

**Comment by andrewrubin** [comment]
Nice one @marlonmarcello thanks for the links 🔥 
I'm wondering if this would slow down our compilation time considerably… I guess I'll have to dig into the code on that `image-size` package. Hopefully it doesn't download the image first. Maybe it just reads some meta data or something

**Comment by marlonmarcello** [comment]
That's my guess too Andrew, hopefully it just reads the meta from the file
system.

**Comment by liamegan** [comment]
Regarding the slow down, it's worth mentioning that this function only needs be run when necessary, not for every image.

**Comment by marlonmarcello** [comment]
Was this implemented @liamegan ?

**Comment by liamegan** [comment]
Nope, I'm moving all these tasks to teamwork so that PMs have visibility.
