### ISSUE TITLE
QUESTION: Should locales extend default.

### ISSUE THREAD

**Issue by liamegan** [wethegit/sweet-potato#44]
Currently within locales we have the following structure:

```
pages
├── locales/
│   ├── default.yml
│   ├── en.yml
│   └── fr.yml
├── index.pug
└   ... etc.
```

The question is, should `en.yaml` *extend* `default.yaml`?

I've always felt like this would be helpful, but maybe not. Let me know your thoughts.

**Comment by andrewrubin** [comment]
I am open to this conversation, but I don't think it's a necessary change. Couple reasons:
- In _most_ i18n situations, you would be overwriting everything in a locale file. I say this with the general public usage in mind—I don't know how often developers will need to be extending locales. This is dependent on the project's needs of course.
- You'd have to explicitly overwrite a property with a `null` value if you _don't_ want it on a particular locale. That's not necessarily a deal-breaker though.

If anything, maybe this should be an option in the config. Thoughts?

**Comment by liamegan** [comment]
Yeah that's a good call. This idea kind of grew out of our old use case where we were mixing language and other page variables like tracking params, but that's less of an issue these days.

**Comment by andrewrubin** [comment]
Yeah I agree. Having the "data model" option solves a lot of that nowdays 😎

**Comment by marlonmarcello** [comment]
`default.yml` IS a locale and in most cases it's `EN`, by extending it we would be mixing locales. I don't think that's a good pattern. Even though we have some repetition here I think it's completely fine. Sometimes being too DRY can also be a problem.

**Comment by marlonmarcello** [comment]
Another thing to note is that we name it `default` but the cooker allows it to be set to something different. If `default` seems a bit misleading maybe we change it to `en` as that is more explicit. I [made an option](https://github.com/wethegit/sweet-potato/tree/main/cooker#localesdefaultname) to set that so even though you are using `en` as the name, it wouldn't put it in a subfolder like `es` or `fr`.

**Comment by liamegan** [comment]
I don't think assuming default === en is a good thing. But I hear y'all thanks very much.
